name: Pls
version: '${version}'
main: io.github.md5sha256.pls.PlsPlugin
api-version: 1.19
commands:
  pls:
    description: "Generate and execute commands based on natural language input"
    aliases: ["please"]
  pls-dp:
    description: "Generates a datapack based on natural language input"
  pls-we:
    description: "Generate and executes worldedit commands bases on natural language input" 